In [1]:
import numpy as np

mydict = {}

mydict["foo"] = 3
mydict["bar"] = 34
mydict["quux"] = 1

In [2]:
lst = [("foo",2),("bar",1),("baz",3)]
sorted(lst,key=lambda tpl: tpl[1])

[('bar', 1), ('foo', 2), ('baz', 3)]

In [3]:
mydict

{'bar': 34, 'foo': 3, 'quux': 1}

In [4]:
mydict.get(0) is None

True

In [5]:
for idx,val in mydict.items():
    val += 1

In [6]:
mydict

{'bar': 34, 'foo': 3, 'quux': 1}

In [7]:
sum([value for _,value in mydict.items()])

38

In [8]:
arr = np.array([
    [1,2,3],
    [2,0,8],
    [0,3,0],
    [0,0,0]
])
np.mean(arr,axis=0)

array([ 0.75,  1.25,  2.75])

In [9]:
list( zip(('foo','bar'),['1','2']))

[('foo', '1'), ('bar', '2')]

In [10]:
"fdasf432%#".maketrans("%"," ")

{37: 32}

In [11]:
arr = np.array([1,2,3,4])

arr = np.random.shuffle(arr)

arr


In [12]:
oharr = np.array([
    [1,0,1,0],
    [0,0,0,0],
    [0,1,0,0],
    [0,1,0,0]
])

np.mean(oharr,axis=0)

array([ 0.25,  0.5 ,  0.25,  0.  ])

In [13]:
def foo():
    lst = [1,2,3,4,5]
    
    for i in lst:
        yield i
    

In [14]:
bar = foo()

In [15]:
bool = True

In [16]:
if bool is True:
    print("y")

y


In [22]:
np.logspace(-2, 7, 10)

array([  1.00000000e-02,   1.00000000e-01,   1.00000000e+00,
         1.00000000e+01,   1.00000000e+02,   1.00000000e+03,
         1.00000000e+04,   1.00000000e+05,   1.00000000e+06,
         1.00000000e+07])

In [31]:
np.logspace(-8, 2, 11)

array([  1.00000000e-08,   1.00000000e-07,   1.00000000e-06,
         1.00000000e-05,   1.00000000e-04,   1.00000000e-03,
         1.00000000e-02,   1.00000000e-01,   1.00000000e+00,
         1.00000000e+01,   1.00000000e+02])

In [34]:
np.logspace(-10,-1,10)

array([  1.00000000e-10,   1.00000000e-09,   1.00000000e-08,
         1.00000000e-07,   1.00000000e-06,   1.00000000e-05,
         1.00000000e-04,   1.00000000e-03,   1.00000000e-02,
         1.00000000e-01])