In [1]:
import numpy as np

mydict = {}

mydict["foo"] = 3
mydict["bar"] = 34
mydict["quux"] = 1

In [2]:
lst = [("foo",2),("bar",1),("baz",3)]
sorted(lst,key=lambda tpl: tpl[1])

[('bar', 1), ('foo', 2), ('baz', 3)]

In [3]:
mydict

{'bar': 34, 'foo': 3, 'quux': 1}

In [4]:
mydict.get(0) is None

True

In [5]:
for idx,val in mydict.items():
    val += 1

In [6]:
mydict

{'bar': 34, 'foo': 3, 'quux': 1}

In [7]:
sum([value for _,value in mydict.items()])

38

In [13]:
arr = np.array([
    [1,2,3],
    [2,0,8],
    [0,3,0],
    [0,0,0]
])
np.mean(arr,axis=0)

array([ 0.75,  1.25,  2.75])

In [10]:
good_tag_indices = np.where(tag_sums>4)

good_tag_indices



(array([1, 2]),)

In [11]:
arr.T[good_tag_indices].T

array([[2, 3],
       [0, 8],
       [3, 0],
       [0, 0]])

In [12]:
list( zip(('foo','bar'),['1','2']))

[('foo', '1'), ('bar', '2')]

In [13]:
"fdasf432%#".maketrans("%"," ")

{37: 32}

In [16]:
arr = np.array([1,2,3,4])

arr = np.random.shuffle(arr)

arr


array([1, 4, 2, 3])

In [16]:
oharr = np.array([
    [1,0,1,0],
    [0,0,0,0],
    [0,1,0,0],
    [0,1,0,0]
])

np.mean(oharr,axis=0)

array([ 0.25,  0.5 ,  0.25,  0.  ])

In [17]:
def foo():
    lst = [1,2,3,4,5]
    
    for i in lst:
        yield i
    

In [18]:
bar = foo()

In [20]:
bool = True

In [22]:
if bool is True:
    print("y")

y
