In [4]:
import numpy as np

mydict = {}

mydict["foo"] = 3
mydict["bar"] = 34
mydict["quux"] = 1

In [11]:
lst = [("foo",2),("bar",1),("baz",3)]
sorted(lst,key=lambda tpl: tpl[1])

[('bar', 1), ('foo', 2), ('baz', 3)]

In [7]:
mydict

{'bar': 34, 'foo': 3, 'quux': 1}

In [14]:
mydict.get(0) is None

True

In [17]:
for idx,val in mydict.items():
    val += 1

In [18]:
mydict

{1: 0.232, 2: 0.654}

In [23]:
sum([value for _,value in mydict.items()]) / 

0.886

In [33]:
arr = np.array([
    [1,2,3],
    [2,0,8],
    [0,3,0],
    [0,0,0]
])
tag_sums = np.sum(arr,axis=0)
tag_sums

array([ 3,  5, 11])

In [34]:
good_tag_indices = np.where(tag_sums>4)

good_tag_indices



(array([1, 2]),)

In [42]:
arr.T[good_tag_indices].T

array([[2, 3],
       [0, 8],
       [3, 0],
       [0, 0]])

In [43]:
list( zip(('foo','bar'),['1','2']))

[('foo', '1'), ('bar', '2')]

In [1]:
"fdasf432%#".maketrans("%"," ")

{37: 32}