In [1]:
import os,sys
import numpy as np

In [2]:
module_path = os.path.abspath(os.path.join('../embedding-classif/'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [3]:
from helpers import tags_helper

In [4]:
strategy = "top_k"
arr = np.array([0.09,0.32,0.321,0.450,0.9,0.2,0.4,0.001])
tags = np.array([
    [1,0,0,0,1,0,0],
    [0,1,0,1,0,0,1],
    [0,0,0,0,0,1,1],
    [0,0,0,1,0,0,1],
    [0,0,0,0,0,0,1]
])

tags_index = tags_helper.get_incidence_index(tags)
tags_index

{0: 0.20000000000000001,
 1: 0.20000000000000001,
 2: 0.0,
 3: 0.40000000000000002,
 4: 0.20000000000000001,
 5: 0.20000000000000001,
 6: 0.80000000000000004}

In [5]:
tags_helper.get_tag_assignment("raw_probability",
                               arr,
                               probability_threshold=0.01,
                               limit=5)

array([[0, 1, 1, 1, 1, 0, 1, 0]])

In [6]:
tags_helper.get_tag_assignment("absolute_difference_wrt_tag_incidence",
                               arr,
                               tag_incidence_index = tags_index,
                               limit=5)

array([[0, 1, 1, 1, 1, 1, 0, 0]])

In [7]:
tags_helper.get_tag_assignment("relative_difference_wrt_tag_incidence",                           
                               arr,
                               tag_incidence_index = tags_index,
                               limit=5)

array([[0, 1, 1, 1, 1, 1, 0, 0]])

In [8]:
tags_helper.get_tag_assignment("absolute_difference_wrt_estimated_tag_probability",
                                  arr,
                                  training_data = tags,  
                                  tag_probability_index = tags_index,
                                  limit=5)

array([[0, 1, 1, 1, 1, 1, 0, 0]])

In [9]:
tags_helper.get_tag_assignment("relative_difference_wrt_estimated_tag_probability",
                                  arr,
                                  training_data = tags,  
                                  tag_probability_index = tags_index,
                                  limit=5)

array([[0, 1, 1, 1, 1, 1, 0, 0]])